# Generated by Django 4.0.3 on 2022-09-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='breakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_n', models.CharField(max_length=25)),
                ('user_p', models.CharField(max_length=30)),
            ],
        ),
    ]
